FROM node:20

WORKDIR /usr/app

COPY ./.env ./.env

# Express App
COPY ./app/src/package*.json ./src/
RUN npm install --prefix ./src

COPY ./app/src ./src

# React App
WORKDIR /usr/app/client

COPY ./app/client/package*.json ./package.json
COPY ./app/client/package-lock.json ./package-lock.json
RUN npm install

COPY ./app/client/ .

# Inject environment variables into the React app during the build
ARG REACT_APP_SSO_URL
ARG REACT_APP_KILN_PREVIEW_URL
ARG REACT_APP_KILN_URL
ARG REACT_APP_KILN_LEGACY_PREVIEW_URL
ARG REACT_APP_KILN_LEGACY_URL
ENV REACT_APP_SSO_URL=${REACT_APP_SSO_URL}
ENV REACT_APP_KILN_PREVIEW_URL=${REACT_APP_KILN_PREVIEW_URL}
ENV REACT_APP_KILN_URL=${REACT_APP_KILN_URL}
ENV REACT_APP_KILN_LEGACY_PREVIEW_URL=${REACT_APP_KILN_LEGACY_PREVIEW_URL}
ENV REACT_APP_KILN_LEGACY_URL=${REACT_APP_KILN_LEGACY_URL}

RUN cp ../.env .env && npm run build

WORKDIR /usr/app/src

ARG APP_PORT
ENV APP_PORT=${APP_PORT}
EXPOSE ${APP_PORT}

CMD ["sh", "-c", "npx knex migrate:latest && node index.js"]
