apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.env.APP_PORT }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
            - secretRef:
                name: {{ .Values.secretName }}
          volumeMounts:
            - name: env-volume
              mountPath: /usr/app/.env
              subPath: .env
          command:
            - sh
            - -c
            - |
              cp /usr/app/.env ../client/.env && npm run build && npx knex migrate:latest && node index.js
      volumes:
        - name: env-volume
          configMap:
            name: {{ .Values.configMapName }}
