apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-template-repo-to-kiln
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kiln
  policyTypes:
  - Ingress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: kiln
      ports:
      - protocol: TCP
        port: 8080
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: kiln
      ports:
      - protocol: TCP
        port: 8080