apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes: {{ .Values.postgresql.primary.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgresql.primary.persistence.size }}
