apiVersion: v1
kind: Service
metadata:
  name: {{ include "template-repository.name" . }}
  labels:
    {{- include "template-repository.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "template-repository.name" . }}
