---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  clusterIP: None 
  ports:
    - name: postgres
      port: {{ .Values.service.postgresPort }}
      targetPort: {{ .Values.service.postgresPort }}
  selector:
    app: {{ .Release.Name }}-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: app
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
  selector:
    app: {{ .Release.Name }}-app
