apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
  selector:
    app: {{ .Release.Name }}-app
