image:
  repository: postgres
  tag: 13

postgresql:
  username: postgres
  password: postgres
  database: form_templates

  volumePermissions:
    enabled: true

  persistence:
    enabled: true
    size: 512Mi
    storageClass: "standard"