persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    storage: 1Gi

postgresql:
  persistence:
    enabled: true
    size: 1Gi 
  resources:
    requests:
      storage: 1Gi 

volumeClaimTemplates:
- metadata:
    name: data
  spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi
